version: '2'
services:
  shinken:
    build:
      context: stg
    ports:
    - 80
    volumes:
    - ./stg/custom_configs:/etc/shinken/custom_configs
    - ./stg/extra_plugins:/usr/local/custom_plugins
